// Mocks generated by Mockito 5.4.0 from annotations
// in meca_wallet/test/features/explore_store/explore_store_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:meca_wallet/features/explore_store/bloc/get_featured_events_cubit.dart'
    as _i3;
import 'package:meca_wallet/features/explore_store/bloc/get_featured_stores_cubit.dart'
    as _i2;
import 'package:meca_wallet/features/explore_store/bloc/get_hot_coupons_cubit.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetFeaturedStoresState_0 extends _i1.SmartFake
    implements _i2.GetFeaturedStoresState {
  _FakeGetFeaturedStoresState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetFeaturedEventsState_1 extends _i1.SmartFake
    implements _i3.GetFeaturedEventsState {
  _FakeGetFeaturedEventsState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetHotCoupounsState_2 extends _i1.SmartFake
    implements _i4.GetHotCoupounsState {
  _FakeGetHotCoupounsState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetFeaturedStoresCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFeaturedStoresCubit extends _i1.Mock
    implements _i2.GetFeaturedStoresCubit {
  MockGetFeaturedStoresCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetFeaturedStoresState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeGetFeaturedStoresState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.GetFeaturedStoresState);
  @override
  _i5.Stream<_i2.GetFeaturedStoresState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.GetFeaturedStoresState>.empty(),
      ) as _i5.Stream<_i2.GetFeaturedStoresState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> getFeaturedStores() => (super.noSuchMethod(
        Invocation.method(
          #getFeaturedStores,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  void emit(_i2.GetFeaturedStoresState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i6.Change<_i2.GetFeaturedStoresState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GetFeaturedEventsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFeaturedEventsCubit extends _i1.Mock
    implements _i3.GetFeaturedEventsCubit {
  MockGetFeaturedEventsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetFeaturedEventsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeGetFeaturedEventsState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.GetFeaturedEventsState);
  @override
  _i5.Stream<_i3.GetFeaturedEventsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.GetFeaturedEventsState>.empty(),
      ) as _i5.Stream<_i3.GetFeaturedEventsState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> getFeaturedEvents() => (super.noSuchMethod(
        Invocation.method(
          #getFeaturedEvents,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  void emit(_i3.GetFeaturedEventsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i6.Change<_i3.GetFeaturedEventsState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GetHotCoupounsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHotCoupounsCubit extends _i1.Mock
    implements _i4.GetHotCoupounsCubit {
  MockGetHotCoupounsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GetHotCoupounsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeGetHotCoupounsState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.GetHotCoupounsState);
  @override
  _i5.Stream<_i4.GetHotCoupounsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i4.GetHotCoupounsState>.empty(),
      ) as _i5.Stream<_i4.GetHotCoupounsState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> getHotCoupouns() => (super.noSuchMethod(
        Invocation.method(
          #getHotCoupouns,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  void emit(_i4.GetHotCoupounsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i6.Change<_i4.GetHotCoupounsState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
