// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcpuXxqKS9pW8dxa7LVDx3JD-QH6Jc_Qs',
    appId: '1:514069798802:web:f8fba6b853f675974a6b4b',
    messagingSenderId: '514069798802',
    projectId: 'micro7-meca-wallet',
    authDomain: 'micro7-meca-wallet.firebaseapp.com',
    storageBucket: 'micro7-meca-wallet.appspot.com',
    measurementId: 'G-GQRCQPTF20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjJnefvIQ9klI6P3AApSUE95fb7BpRNcQ',
    appId: '1:514069798802:android:bca553a9b28da9e04a6b4b',
    messagingSenderId: '514069798802',
    projectId: 'micro7-meca-wallet',
    storageBucket: 'micro7-meca-wallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEW4ovtGdj5A2iOvz19L2xLsu2dZE23GQ',
    appId: '1:514069798802:ios:ed02800f80e2a3764a6b4b',
    messagingSenderId: '514069798802',
    projectId: 'micro7-meca-wallet',
    storageBucket: 'micro7-meca-wallet.appspot.com',
    iosClientId: '514069798802-ltq34hhf93ptuuhdiumhtudepje7bc58.apps.googleusercontent.com',
    iosBundleId: 'com.micro7.mecaWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEW4ovtGdj5A2iOvz19L2xLsu2dZE23GQ',
    appId: '1:514069798802:ios:ed02800f80e2a3764a6b4b',
    messagingSenderId: '514069798802',
    projectId: 'micro7-meca-wallet',
    storageBucket: 'micro7-meca-wallet.appspot.com',
    iosClientId: '514069798802-ltq34hhf93ptuuhdiumhtudepje7bc58.apps.googleusercontent.com',
    iosBundleId: 'com.micro7.mecaWallet',
  );
}
